name: Sync & Purge
on:
  push:
    branches: [main]
jobs:
  sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Sync to Gitee
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add gitee "https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/zhyao333/baojiadan-update.git"
          git push --force gitee main:master
      - name: Purge jsDelivr
        run: curl -sS "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/version.json"
