name: Purge jsDelivr Cache
on:
  push:
    branches: [main]
jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr
        run: curl -sS "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/version.json"
